image: php:7-fpm

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -y python-dev zip libmcrypt-dev mariadb-client libpng-dev
            - docker-php-ext-install mcrypt && docker-php-ext-install pdo_mysql && docker-php-ext-install gd && docker-php-ext-configure intl && docker-php-ext-install intl
            - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
            - php -r "if (hash_file('sha384', 'composer-setup.php') === 'baf1608c33254d00611ac1705c1d9958c817a1a33bce370c0595974b342601bd80b92a3f46067da89e3b06bff421f182') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
            - php composer-setup.php
            - php -r "unlink('composer-setup.php');"
            - php composer.phar install
            - php artisan migrate
            - curl -O https://bootstrap.pypa.io/get-pip.py
            - python get-pip.py
            - pip install awscli
            - zip -r deploy.zip ./
            - aws s3 sync --delete . s3://simple-backend